title: "Kelina Cowell â€“ QA Portfolio"
description: "Multiplatform Games Tester | Functional, Exploratory, and Cross-Platform QA"
theme: minima
minima:
  skin: classic
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/kelina-cowell-qa-tester" }
